export const SHEETS = {
  PRODUCT_MASTER: 'PRODUCT_MASTER',
  SALES_HEADER: 'SALES_HEADER',
  SALES_ITEMS: 'SALES_ITEMS',
  STOCK_MOVEMENTS: 'STOCK_MOVEMENTS',
  DAILY_SUMMARY: 'DAILY_SUMMARY',
  CONFIG: 'CONFIG',
  USERS: 'USERS',
} as const;

export type SheetName = keyof typeof SHEETS;
